from ROOT import *
from math import *
#-------------------------------------------------------------------------------
rootfile ='/eos/uscms/store/group/lpchbb/LLDJntuples/topRWT/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/crab_DY50_1/180928_181036/0000/lldjntuple_mc_AOD_1.root'


sample ='DY50'   
# read all entries and fill the histograms
c1 = TCanvas('c1', 'Histogram', 200, 10, 700, 900)
hpt = TH1F("hpt",'%s Ntuple AOD_ele pt hist' % sample, 50, 0, 200)
heta = TH1F("heta","%s MC Ntuple AOD_ele eta hist" % sample, 100, -3, 3)
hE = TH1F("hE","%s MC Ntuple AOD_ele Energy hist" % sample, 50, 0, 200)
hEUp = TH1F("hEUp","%s MC Ntuple AOD_ele E hist UncUp" % sample, 50, 0, 200)
hEDown = TH1F("hEDown","%s MC Ntuple AOD_ele E hist UncDown" % sample, 50, 0, 200)
hSize = TH1I("hSize","%s MC Ntuple AOD_ele event number" % sample, 8, 0, 8)
h1E = TH1F("h1E","%s MC Ntuple AOD_ele Ehist -1e" % sample, 50, 0, 200)
h2E = TH1F("h2E","%s MC Ntuple AOD_ele Ehist -2e" % sample, 50, 0, 200)
h3E = TH1F("h3E","%s MC Ntuple AOD_ele Ehist -3e" % sample, 50, 0, 200)
hmuonn = TH1I("hmuonn","%s MC Ntuple AOD_muon # at nele = 1" % sample, 8, 0, 8) 
hmE = TH1F("hmE","%s MC Ntuple AOD_muon pt" % sample, 50, 0, 200)
hmuonn2 = TH1I("hmuonn2","%s MC Ntuple AOD_muon # at nele = 2" % sample, 8, 0, 8) 
hmE2 = TH1F("hmE2","%s MC Ntuple AOD_muon pt ne2" % sample, 50, 0, 200)
hmuonn3 = TH1I("hmuonn3","%s MC Ntuple AOD_muon # at nele = 3" % sample, 8, 0, 8) 
hmE3 = TH1F("hmE3","%s MC Ntuple AOD_muon pt ne3" % sample, 50, 0, 200)
hphon=  TH1I("hphon","%s MC Ntuple AOD_pho # at nele = 1" % sample, 8, 0, 8) 
hphon2= TH1I("hphon2","%s MC Ntuple AOD_pho # at nele = 2" % sample, 8, 0, 8) 
hphon3= TH1I("hphon3","%s MC Ntuple AOD_pho # at nele = 3" % sample, 8, 0, 8) 
hjetn=  TH1I("hjetn","%s MC Ntuple AOD_jet # at nele = 1" % sample, 8, 0, 8) 
hjetn2= TH1I("hjetn2","%s MC Ntuple AOD_jet # at nele = 2" % sample, 8, 0, 8) 
hjetn3= TH1I("hjetn3","%s MC Ntuple AOD_jet # at nele = 3" % sample, 8, 0, 8) 

hphoE1 = TH1F("hphoE","%s MC Ntuple AOD_pho pt" % sample, 50, 0, 200)
hphoE2 = TH1F("hphoE2","%s MC Ntuple AOD_pho pt" % sample, 50, 0, 200)
hphoE3 = TH1F("hphoE3","%s MC Ntuple AOD_pho pt" % sample, 50, 0, 200)
hjetE1 = TH1F("hjetE","%s MC Ntuple AOD_jet pt" % sample, 50, 0, 200)
hjetE2 = TH1F("hjetE2","%s MC Ntuple AOD_jet pt" % sample, 50, 0, 200)
hjetE3 = TH1F("hjetE3","%s MC Ntuple AOD_jet pt" % sample, 50, 0, 200)


pad1 = TPad( 'pad1', 'The pad with the function',  0.03, 0.62, 0.50, 0.92, 21 )
pad2 = TPad( 'pad2', 'The pad with the histogram', 0.51, 0.62, 0.98, 0.92, 21 )
pad3 = TPad( 'pad3', 'The pad with the histogram', 0.03, 0.02, 0.97, 0.57, 21 )





myfile = TFile.Open(rootfile)
mytree = myfile.Get("lldjNtuple/EventTree")
entries = mytree.GetEntries()
mytree.Print()     
print(entries)
pt = mytree.GetLeaf("AOD_elePt")
print(pt)
ePt = std.vector('float')(1) 
print(ePt)
mytree.SetBranchAddress("AOD_elePt",ePt)	
print(ePt)
Eta = mytree.GetLeaf("AOD_eleEta")
print(Eta)
eEta = std.vector('float')(1)  
print(eEta)
mytree.SetBranchAddress("AOD_eleEta",eEta)        
print(eEta)
mPt = std.vector('float')(1)
print(mPt)
mytree.SetBranchAddress("AOD_muPt",mPt)
print(mPt)
mEta = std.vector('float')(1)
print(mEta)
mytree.SetBranchAddress("AOD_muEta",mEta)        
print(mEta)
pPt = std.vector('float')(1)
print(pPt)
mytree.SetBranchAddress("AOD_phoPt",pPt)
print(pPt)
pEta = std.vector('float')(1)
print(pEta)
mytree.SetBranchAddress("AOD_phoEta",pEta)        
print(pEta)
jPt = std.vector('float')(1)
print(jPt)
mytree.SetBranchAddress("AODCaloJetPt",jPt)
print(jPt)
jEta = std.vector('float')(1)
print(jEta)
mytree.SetBranchAddress("AODCaloJetEta",jEta)        
print(jEta)

for i in range(entries):      
	numpy = mytree.GetEntry(i)
	love = ePt.size()
	hSize.Fill(love,1)
	if love > 0:
		number = int(ePt.size())
		for j in range(number):
			#print(ePt[j])
			#print(eEta[j])
			Energy = ePt[j]*cosh(eEta[j])
			EUp = Energy*1.02
			EDown = Energy*.98
			hpt.Fill(ePt[j],1)
			heta.Fill(eEta[j],1)
			hE.Fill(Energy,1)
		 	hEUp.Fill(EUp,1)
			hEDown.Fill(EDown,1)	
			if number == 1:
				h1E.Fill(Energy,1)
				nmu = int(mPt.size())	
				hmuonn.Fill(nmu,1)
					
				for k in range(nmu):
					mEnergy = mPt[k]*cosh(mEta[k])
					hmE.Fill(mEnergy,1)
				npho = int(pPt.size())
				hphon.Fill(npho,1)
				
				for l in range(npho):
					pEnergy = pPt[l]*cosh(pEta[l])
					hphoE1.Fill(pEnergy,1)
				njet = int(jPt.size())
				hjetn.Fill(njet,1)				 
				
				for m in range(njet):
					jEnergy = jPt[m]*cosh(jEta[m])
					hjetE1.Fill(jEnergy,1)
			elif number == 2:
				h2E.Fill(Energy,1)
				nmu = int(mPt.size())
				hmuonn2.Fill(nmu,1)			 
				
				for k in range(nmu):
					mEnergy = mPt[k]*cosh(mEta[k])
					hmE2.Fill(mEnergy,1)
				npho = int(pPt.size())
				hphon2.Fill(npho,1)
				
				for l in range(npho):
					pEnergy = pPt[l]*cosh(pEta[l])
					hphoE2.Fill(pEnergy,1)
				njet = int(jPt.size())
				hjetn2.Fill(njet,1)				 
				
				for m in range(njet):
					jEnergy = jPt[m]*cosh(jEta[m])
					hjetE2.Fill(jEnergy,1)
			else:
				h3E.Fill(Energy,1)
				nmu = int(mPt.size())
			
				for k in range(nmu):
					mEnergy = mPt[k]*cosh(mEta[k])
					hmE3.Fill(mEnergy,1)
				hmuonn3.Fill(nmu,1)			 
				npho = int(pPt.size())
				hphon3.Fill(npho,1)
				
				for l in range(npho):
					pEnergy = pPt[l]*cosh(pEta[l])
					hphoE3.Fill(pEnergy,1)
				njet = int(jPt.size())
				hjetn3.Fill(njet,1)				 
				
				for m in range(njet):
					jEnergy = jPt[m]*cosh(jEta[m])
					hjetE3.Fill(jEnergy,1)

hSize.Draw('HIST')
c1.Modified()
c1.Update()
c1.SaveAs('%shSize.png' % sample)
hpt.Draw('HIST')
c1.Modified()
c1.Update()
c1.SaveAs('%shpt.png' % sample)
heta.Draw('HIST')
c1.Modified()
c1.Update()
c1.SaveAs('%sheta.png' % sample)

hE.GetXaxis().SetTitle('Electron pt (GeV)')
hE.GetYaxis().SetTitle('Counts')
hE.Draw('HIST')
hE.SetFillColor(42)
hEUp.SetMarkerStyle(21)
hEUp.SetMarkerColor(2)
hEUp.Draw('P SAME')
hEDown.SetMarkerStyle(22)
hEDown.SetMarkerColor(3)
hEDown.Draw('P SAME')
legend = TLegend(0.7,0.65,0.9,0.75)
legend.AddEntry(hEUp,"Electron pt EGSUp","lep")
legend.AddEntry(hEDown,"Electron pt EGSDown","lep")
legend.Draw()
c1.Modified()
c1.Update()
c1.SaveAs('%shE.png' % sample)
h1E.GetXaxis().SetTitle('Electron pt (GeV)')
h1E.GetYaxis().SetTitle('Counts')
h1E.GetYaxis().SetRangeUser(0,500)
h1E.Draw('HIST')
h1E.SetFillColor(42)
h2E.SetMarkerStyle(21)
h2E.SetMarkerColor(2)
h2E.Draw('P SAME')
h3E.SetMarkerStyle(22)
h3E.SetMarkerColor(3)
h3E.Draw('P SAME')
legend2 = TLegend(0.7,0.65,0.9,0.75)
legend2.AddEntry(h2E,"2 electrons event","lep")
legend2.AddEntry(h3E,"#geq3 electrons event","lep")
legend2.Draw()
c1.Modified()
c1.Update()
c1.SaveAs('%shComparison.png' % sample)
pad1.Draw()
pad2.Draw()
pad3.Draw()
pad1.cd()
hmuonn.GetXaxis().SetTitle('Muon event #')
hmuonn.GetYaxis().SetTitle('Counts')
hmuonn.GetYaxis().SetRangeUser(0,2500)
hmuonn.Draw('HIST')
hmuonn.SetFillColor(42)
hmuonn2.SetMarkerStyle(21)
hmuonn2.SetMarkerColor(2)
hmuonn2.Draw('P SAME')
hmuonn3.SetMarkerStyle(22)
hmuonn3.SetMarkerColor(3)
hmuonn3.Draw('P SAME')
legend3 = TLegend(0.7,0.65,0.9,0.75)
legend3.AddEntry(hmuonn2,"2 electrons event","lep")
legend3.AddEntry(hmuonn3,"#geq3 electrons event","lep")
legend3.Draw()
#c1.Modified()
#c1.Update()
#c1.SaveAs('%shmuonnumber.png' % sample)
pad2.cd()
hphon.GetXaxis().SetTitle('Photon event #')
hphon.GetYaxis().SetTitle('Counts')
hphon.GetYaxis().SetRangeUser(0,3000)
hphon.Draw('HIST')
hphon.SetFillColor(42)
hphon2.SetMarkerStyle(21)
hphon2.SetMarkerColor(2)
hphon2.Draw('P SAME')
hphon3.SetMarkerStyle(22)
hphon3.SetMarkerColor(3)
hphon3.Draw('P SAME')
legend4 = TLegend(0.7,0.65,0.9,0.75)
legend4.AddEntry(hphon2,"2 electrons event","lep")
legend4.AddEntry(hphon3,"#geq3 electrons event","lep")
legend4.Draw()
#c1.Modified()
#c1.Update()
#c1.SaveAs('%shphonumber.png' % sample)
pad3.cd()
hjetn.GetXaxis().SetTitle('Jet event #')
hjetn.GetYaxis().SetTitle('Counts')
hjetn.GetYaxis().SetRangeUser(0,3000)
hjetn.Draw('HIST')
hjetn.SetFillColor(42)
hjetn2.SetMarkerStyle(21)
hjetn2.SetMarkerColor(2)
hjetn2.Draw('P SAME')
hjetn3.SetMarkerStyle(22)
hjetn3.SetMarkerColor(3)
hjetn3.Draw('P SAME')
legend5 = TLegend(0.7,0.65,0.9,0.75)
legend5.AddEntry(hjetn2,"2 electrons event","lep")
legend5.AddEntry(hjetn3,"#geq3 electrons event","lep")
legend5.Draw()
c1.Modified()
c1.Update()
c1.SaveAs('%shmuonphojetnumber.png' % sample)
hmE.GetXaxis().SetTitle('muon pt (GeV)')
hmE.GetYaxis().SetTitle('Counts')
hmE.GetYaxis().SetRangeUser(0,2000)
hmE.Draw('HIST')
hmE.SetFillColor(42)
hmE2.SetMarkerStyle(21)
hmE2.SetMarkerColor(2)
hmE2.Draw('P SAME')
hmE3.SetMarkerStyle(22)
hmE3.SetMarkerColor(3)
hmE3.Draw('P SAME')
legend6 = TLegend(0.7,0.65,0.9,0.75)
legend6.AddEntry(hmE2,"2 electrons event","lep")
legend6.AddEntry(hmE3,"#geq3 electrons event","lep")
legend6.Draw()
c1.Modified()
c1.Update()
c1.SaveAs('%smuonE.png' % sample)
hphoE1.GetXaxis().SetTitle('photon pt (GeV)')
hphoE1.GetYaxis().SetTitle('Counts')
hphoE1.GetYaxis().SetRangeUser(0,1000)
hphoE1.Draw('HIST')
hphoE1.SetFillColor(42)
hphoE2.SetMarkerStyle(21)
hphoE2.SetMarkerColor(2)
hphoE2.Draw('P SAME')
hphoE3.SetMarkerStyle(22)
hphoE3.SetMarkerColor(3)
hphoE3.Draw('P SAME')
legend7 = TLegend(0.7,0.65,0.9,0.75)
legend7.AddEntry(hphoE2,"2 electrons event","lep")
legend7.AddEntry(hphoE3,"#geq3 electrons event","lep")
legend7.Draw()
c1.Modified()
c1.Update()
c1.SaveAs('%sphoE.png' % sample)
hjetE1.GetXaxis().SetTitle('jet pt (GeV)')
hjetE1.GetYaxis().SetTitle('Counts')
hjetE1.GetYaxis().SetRangeUser(0,500)
hjetE1.Draw('HIST')
hjetE1.SetFillColor(42)
hjetE2.SetMarkerStyle(21)
hjetE2.SetMarkerColor(2)
hjetE2.Draw('P SAME')
hjetE3.SetMarkerStyle(22)
hjetE3.SetMarkerColor(3)
hjetE3.Draw('P SAME')
legend8 = TLegend(0.7,0.65,0.9,0.75)
legend8.AddEntry(hjetE2,"2 electrons event","lep")
legend8.AddEntry(hjetE3,"#geq3 electrons event","lep")
legend8.Draw()
c1.Modified()
c1.Update()
c1.SaveAs('%sjetE.png' % sample)

