## \file
## \ingroup tutorial_pyroot
## \notebook -js
## A Simple histogram drawing example
##
## \macro_image
## \macro_output
## \macro_code
##
## \author Wim Lavrijsen

from ROOT import *

c1 = TCanvas( 'c1', 'Histogram Drawing Options', 800,800 )
gStyle.SetOptStat(0)
gPad.SetTickx()
gPad.SetTicky()
gStyle.SetLineWidth(3)
gStyle.SetPalette(kBird)

c1.Clear()
#c1.cd()
pad1 = TPad("pad1", "The pad with the function",0,0.25,1,1)
pad1.SetBottomMargin(0.04)
pad1.SetLeftMargin(.12)
pad1.SetRightMargin(.05)
pad1.SetFrameLineWidth(3)


pad1.Draw()
c1.cd()
pad2 = TPad("pad2", "The pad with the ratio plot",0,0,1,0.25)
pad2.SetTopMargin(0.04)
pad2.SetBottomMargin(0.4)
pad2.SetLeftMargin(.12)
pad2.SetRightMargin(.05)
pad2.SetFrameLineWidth(3)
pad2.SetGrid()
pad2.Draw()
c1.cd()
h0 = TH1F()
h1 = TH1F()
#gStyle.SetOptStat(0)
_file0 = TFile.Open('None/DYJetsToLL_M-50_TwoMuDY_histograms.root','read')
_file1 = TFile.Open('ID/DYJetsToLL_M-50_TwoMuDY_histograms.root','read')
_file2 = TFile.Open('IDISO/DYJetsToLL_M-50_TwoMuDY_histograms.root','read')
_file3 = TFile.Open('All/DYJetsToLL_M-50_TwoMuDY_histograms.root','read')
_file4 = TFile.Open('99/DYJetsToLL_M-50_TwoMuDY_histograms.root','read')
h0=_file0.Get('h_TwoMuDY_AOD_muPt').Clone('No_SF_Hist')
h1=_file1.Get('h_TwoMuDY_AOD_muPt').Clone('No_SF_Hist')
h2=_file2.Get('h_TwoMuDY_AOD_muPt')
h3=_file3.Get('h_TwoMuDY_AOD_muPt')
h4=_file4.Get('h_TwoMuDY_AOD_muPt')
h_ratio = h3.Clone('ratiohist')
h_ratio.Divide(h4)
#h = _file0.Get('h_TwoEleDY_AOD_elePt')
#h0.SetTitle('DYJetsToLL_M-50 None,ISISO,All,All(.99 for all TrigSF) Dielectron Mass')
pad1.cd()
h0.GetXaxis().SetTitle('muon pt (GeV)')
h0.GetXaxis().SetRangeUser(0,200)
#h0.GetYaxis().SetRangeUser(0,100)
h0.GetYaxis().SetTitle('Counts')
h0.Draw('HIST')
h1.SetFillStyle(3007)
h1.SetFillColor(kBlue)
h1.Draw('HISTSAME')
h2.SetFillStyle(3006)
h2.SetFillColor(kRed)
h2.Draw('HIST SAME')
h3.SetFillStyle(3007)
h3.SetFillColor(kGreen)
h3.Draw('HIST SAME')
h4.SetFillStyle(3006)
h4.SetFillColor(kYellow)
h4.Draw('HIST SAME')
#
legend = TLegend(0.7,0.65,0.9,0.75) 		
legend.AddEntry(h0,"No SF","f")
legend.AddEntry(h1,"ID SF","f")
legend.AddEntry(h2,"IDISO SF","f")
legend.AddEntry(h3,"All SF","f")
legend.AddEntry(h3,"All SF (TrigEffi=.99)","f")
legend.Draw()
pad2.cd()
h_ratio.GetXaxis().SetTitle('electron pt (GeV)')
h_ratio.GetYaxis().SetTitle('All_SF/IDISO_.99Trig')
h_ratio.GetYaxis().SetTitleSize(15)
h_ratio.GetYaxis().SetTitleFont(43)
h_ratio.GetYaxis().SetTitleOffset(2.5)
h_ratio.GetYaxis().SetLabelFont(43)
h_ratio.GetYaxis().SetLabelSize(20)
#h_ratio.GetYaxis().SetNdivisions(-105)
h_ratio.SetTitle('')
h_ratio.GetXaxis().SetTitleSize(20)
h_ratio.GetXaxis().SetTitleFont(43)
h_ratio.GetXaxis().SetTitleOffset(4.0)
h_ratio.GetXaxis().SetLabelFont(43)
h_ratio.GetXaxis().SetLabelSize(20)
h_ratio.SetMarkerStyle(20)
h_ratio.SetMarkerColor(kRed)
h_ratio.SetMarkerSize(1)

h_ratio.GetXaxis().SetRangeUser(0,200)
h_ratio.GetYaxis().SetRangeUser(0.7,1.3)
h_ratio.Draw('hist p')
c1.Update()
line = TLine(pad2.GetUxmin(),1.0,pad2.GetUxmax(),1.0)
line.SetLineColor(kBlue)
line.SetLineWidth(3)
line.SetLineStyle(9)
line.Draw('')
#h2 = _file0.Get('h_TwoEleDY_AOD_elePt_EGSUp')
#h2.Draw('SAME e1')

#_file1 = TFile.Open('../roots/Systematics2/DYJetsToLL_M-5to50_HT-600toInf_TwoEleDY_histograms.root','read')
#h3 = _file1.Get('h_TwoEleDY_AOD_elePt')
#h3.Draw('SAME HIST')
#h4 = _file1.Get('h_TwoEleDY_AOD_elePt_EGSUp')
#h4.Draw('SAME e1')

c1.Modified()
c1.Update()
#c1.SaveAs('xo.png')
k=raw_input('Press ENTER to exit')
